logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/mobilelele_db?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
        open-in-view: false
        properties:
            hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            format_sql: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true
